server.port=8080
server.address=0.0.0.0
spring.application.name=petitbac-v2
spring.web.resources.static-locations=classpath:/static/
app.db.path=petitbac-v2.db
spring.datasource.url=jdbc:sqlite:./petitbac-v2.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=false